# 应用配置
app:
  name: "gin-demo"
  version: "1.0.0"
  env: "development"
  debug: true

# 服务器配置
server:
  port: 8080
  mode: "debug"
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "10s"
  max_header_bytes: 1048576
  max_request_size: 10485760  # 10MB
  # 限流配置
  rate_limit:
    global:
      limit: 10
      window: "1m"  # 1分钟
    auth:
      limit: 20
      window: "1m"  # 认证接口更严格的限流

# 数据库配置
database:
  mysql:
    host: "127.0.0.1"
    port: 3306
    username: "root"
    password: "123456"
    database: "daka_dev"
    charset: "utf8mb4"
    parse_time: true
    loc: "Local"
    max_idle_conns: 20
    max_open_conns: 100
    conn_max_lifetime: "3600s"
    conn_max_idle_time: "1800s"
    dial_timeout: "10s"
    read_timeout: "30s"
    write_timeout: "30s"
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    pool_size: 20
    min_idle_conns: 5
    max_retries: 3
    pool_timeout: "30s"
    conn_max_idle_time: "1800s"
    dial_timeout: "10s"
    read_timeout: "10s"
    write_timeout: "10s"

# JWT配置
jwt:
  secret: "your-super-secret-jwt-key-change-this-in-production-2024"
  expires_hours: 168
  refresh_expires_hours: 720
  issuer: "gin-demo"

# 日志配置
log:
  level: "info"
  format: "json"
  enable_color: true
  enable_caller: false
  enable_stacktrace: false
  console:
    enabled: true
    level: "info"
    format: "text"
    enable_color: true
  file:
    enabled: true
    level: "info"
    format: "json"
    filename: "./logs/app.log"
    max_size: 10
    max_backups: 30
    max_age: 7
    compress: true
  error_file:
    enabled: true
    level: "error"
    format: "json"
    filename: "./logs/error.log"
    max_size: 10
    max_backups: 20
    max_age: 7
    compress: true
  database:
    enabled: true
    level: "info"
    slow_threshold: 200
    log_all_sql: true
    ignore_record_not_found: true
    filename: "./logs/database.log"
    max_size: 10
    max_backups: 30
    max_age: 7
    compress: true
  access:
    enabled: true
    format: "json"
    filename: "./logs/access.log"
    max_size: 10
    max_backups: 30
    max_age: 7
    compress: true